services:
  frontend:
    image: node:17.5.0-slim
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 80
      WS_PORT: 81
      BASE_URL: http://localhost
    ports:
      - 82:80
      - 83:81
    env_file:
      - .env
    tty: true
