services:
  frontend:
    image: node:17.5.0-slim
    volumes:
      - ./frontend:/app:delegated
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 80
      WS_PORT: 83
      BASE_URL: http://localhost
    ports:
      - 82:80
      - 83:83
    env_file:
      - .env
    command: bash -c 'cd ./task-choice/ && npm install && npm run dev -- --host 0.0.0.0 --port 80'
